** HEADER -----------------------------------------------------
**  DO-FILE METADATA
    //  algorithm name          StephanieDate_EndoCancer.do
    //  project:                DataGroup
    //  analysts:               Jacqueline CAMPBELL
    //  date first created      10-JUN-2020
    // 	date last modified      11-JUN-2020
    //  algorithm task          Prep, format and filter death data 2008-2018
    //  status                  Completed
    //  objectve                To have one dataset with 2008-2018 endometrial cancer-related deaths.
    //  note                    2008-2020 REDCap death database used.

    
    ** General algorithm set-up
    version 16
    clear all
    macro drop _all
    set more off

    ** Initialising the STATA log and allow automatic page scrolling
    capture {
            program drop _all
    	drop _all
    	log close
    	}

    ** Set working directories: this is for DATASET and LOGFILE import and export
    ** DATASETS to encrypted SharePoint folder
    local datapath "X:/The University of the West Indies/DataGroup - repo_data/data_p131"
    ** LOGFILES to unencrypted OneDrive folder (.gitignore set to IGNORE log files on PUSH to GitHub)
    local logpath X:/OneDrive - The University of the West Indies/repo_datagroup/repo_p131

    ** Close any open log file and open a new log file
    capture log close
    log using "`logpath'\StephanieDate_EndoCancer.smcl", replace
** HEADER -----------------------------------------------------

********************
** DATA PREPARATION  
********************
** LOAD the national registry deaths 2008-2017 excel dataset
import excel using "`datapath'\version05\1-input\BNRDeathData20082020_DATA_2020-06-10_excel.xlsx" , firstrow case(lower)

count //29,100

** Create 2008-2018 dataset
tab dodyear ,m 
list record_id redcap_event_name if dodyear==. //all tracking
list record_id if dodyear==. & redcap_event_name=="death_data_collect_arm_1" //0
drop if redcap_event_name=="tracking_arm_2" //126 deleted
//drop if dodyear>2018 //2137 deleted
count if namematch==3 //2
list record_id duprec if namematch==3
drop if namematch==3 //2 deleted

count //26,972

** Format dataset
************************
**  DEATH CERTIFICATE **
**        FORM        **
************************

** (1) record_id (auto-generated by REDCap)
label var record_id "DeathID"

** (9) pname: Text, if missing=99
label var pname "Deceased's Name"
replace pname = rtrim(ltrim(itrim(pname))) //5 changes

** (10) address: Text, if missing=99
label var address "Deceased's Address"
replace address = rtrim(ltrim(itrim(address))) //20 changes

** (11) parish
label var parish "Deceased's Parish"
label define parish_lab 1 "Christ Church" 2 "St. Andrew" 3 "St. George" 4 "St. James" 5 "St. John" 6 "St. Joseph" ///
						7 "St. Lucy" 8 "St. Michael" 9 "St. Peter" 10 "St. Philip" 11 "St. Thomas" 99 "ND", modify
label values parish parish_lab

** (12) sex:	1=Male 2=Female 99=ND
label var sex "Sex"
label define sex_lab 1 "Male" 2 "Female" 99 "ND", modify
label values sex sex_lab

** (13) age: Integer - min=0, max=999
label var age "Age"

** (14) agetxt
label var agetxt "Age Qualifier"
label define agetxt_lab 1 "Minutes" 2 "Hours" 3 "Days" 4 "Weeks" 5 "Months" 6 "Years" 99 "ND", modify
label values agetxt agetxt_lab

** (15) nrnnd: 1=Yes 2=No
label var nrnnd "Is National ID # documented?"

** (16) nrn: dob-####, partial missing=dob-9999, if missing=.
label var nrn "National ID #"
format nrn %15.0g

** (18) occu: Text, if missing=99
label var occu "Occupation"

** (19) durationnum: Integer - min=0, max=99, if missing=99
label var durationnum "Duration of Illness"

** (20) durationtxt
label var durationtxt "Duration Qualifier"
label define durationtxt_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values durationtxt durationtxt_lab

** (21) dod: Y-M-D
format dod %tdCCYY-NN-DD
label var dod "Date of Death"

** (22) dodyear
label var dodyear "Year of Death"

** (23) cod1a: Text, if missing=99
label var cod1a "COD 1a"

** (24) onsetnumcod1a: Integer - min=0, max=99, if missing=99
label var onsetnumcod1a "Onset Death Interval-COD 1a"

** (25) onsettxtcod1a: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod1a "Onset Qualifier-COD 1a"
label define onsettxtcod1a_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod1a onsettxtcod1a_lab

** (26) cod1b: Text, if missing=99
label var cod1b "COD 1b"

** (27) onsetnumcod1b: Integer - min=0, max=99, if missing=99
label var onsetnumcod1b "Onset Death Interval-COD 1b"

** (28) onsettxtcod1b: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod1b "Onset Qualifier-COD 1b"
label define onsettxtcod1b_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod1b onsettxtcod1b_lab

** (29) cod1c: Text, if missing=99
label var cod1c "COD 1c"

** (30) onsetnumcod1c: Integer - min=0, max=99, if missing=99
label var onsetnumcod1c "Onset Death Interval-COD 1c"

** (31) onsettxtcod1c: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod1c "Onset Qualifier-COD 1c"
label define onsettxtcod1c_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod1c onsettxtcod1c_lab

** (32) cod1d: Text, if missing=99
label var cod1d "COD 1d"

** (33) onsetnumcod1d: Integer - min=0, max=99, if missing=99
label var onsetnumcod1d "Onset Death Interval-COD 1d"

** (34) onsettxtcod1d: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod1d "Onset Qualifier-COD 1d"
label define onsettxtcod1d_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod1d onsettxtcod1d_lab

** (35) cod2a: Text, if missing=99
label var cod2a "COD 2a"

** (36) onsetnumcod2a: Integer - min=0, max=99, if missing=99
label var onsetnumcod2a "Onset Death Interval-COD 2a"

** (37) onsettxtcod2a: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod2a "Onset Qualifier-COD 2a"
label define onsettxtcod2a_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod2a onsettxtcod2a_lab

** (38) cod2b: Text, if missing=99
label var cod2b "COD 2b"

** (39) onsetnumcod2b: Integer - min=0, max=99, if missing=99
label var onsetnumcod2b "Onset Death Interval-COD 2b"

** (40) onsettxtcod2b: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod2b "Onset Qualifier-COD 2b"
label define onsettxtcod2b_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod2b onsettxtcod2b_lab


** Create dataset with variables for Stephanie Date to use for matching with her participants
drop redcap_event_name dddoa ddda odda certtype regnum district mstatus occu pod deathparish ///
	 regdate certifier certifieraddr namematch duprec cleaned death_certificate_complete ///
	 tfdddoa tfddda tfregnumstart tfdistrictstart tfregnumend tfdistrictend tfddtxt tracking_complete

** Create full dataset with all deaths
count //26.835
label data "BNR MORTALITY data 2008-2019"
notes _dta :These data prepared from BB national death register & Redcap deathdata database
save "`datapath'\version05\2-working\2008-2019_deaths_all" ,replace

** Export full death dataset and share via encrypted Sync link
sort record_id
export_excel using "`datapath'\version05\3-output\2020-06-12_AllDeaths_2008-2019_variables.xlsx", firstrow(variables) replace
export_excel using "`datapath'\version05\3-output\2020-06-12_AllDeaths_2008-2019_labels.xlsx", firstrow(varlabels) replace

** Create Endometrial cancer-related dataset
count if regexm(cod1a, "ENDOMET") //179; 193
count if regexm(cod1b, "ENDOMET") //5; 8
count if regexm(cod1c, "ENDOMET") //0; 1
count if regexm(cod1d, "ENDOMET") //0
count if regexm(cod2a, "ENDOMET") //0; 1
count if regexm(cod2b, "ENDOMET") //0

list record_id dodyear cod1a if regexm(cod1a, "ENDOMET"), string(130)
list record_id dodyear cod1a cod1b if regexm(cod1b, "ENDOMET"), string(130)
list record_id dodyear cod1a cod1b cod1c if regexm(cod1c, "ENDOMET"), string(130)
list record_id dodyear cod1a cod1b cod1c cod2a if regexm(cod2a, "ENDOMET"), string(130)
keep if regexm(cod1a, "ENDOMET")|regexm(cod1b, "ENDOMET")|regexm(cod1c, "ENDOMET")|regexm(cod1d, "ENDOMET")|regexm(cod2a, "ENDOMET")|regexm(cod2b, "ENDOMET") //26,651 deleted

count //184; 202
label data "BNR MORTALITY data 2008-2018: Endometrial cancer deaths"
notes _dta :These data prepared from BB national death register & Redcap deathdata database
save "`datapath'\version05\2-working\2008-2018_deaths_endometrial" ,replace

** Export customized death dataset and share via encrypted Sync link
sort record_id
export_excel using "`datapath'\version05\3-output\2020-06-12_EndometrialCancers_2008-2019_variables.xlsx", firstrow(variables) replace
export_excel using "`datapath'\version05\3-output\2020-06-12_EndometrialCancers_2008-2019_labels.xlsx", firstrow(varlabels) replace